services:
  - type: web
    name: qrcodegenerator
    env: java
    plan: free
    branch: master
    runtime: java17
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/qrcodegenerator-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -XX:+UseSerialGC -Xss512k -XX:MaxRAM=512m
      - key: SERVER_PORT
        value: 10000
    healthCheckPath: /
    healthCheckTimeout: 100
    autoDeploy: false