services:
  - type: web
    name: qrcodegenerator
    env: java
    plan: free
    branch: master
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/qrcodegenerator-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -XX:+UseSerialGC -Xss512k -XX:MaxRAM=512m
      - key: SERVER_PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: false